# Generated by Django 2.0 on 2017-12-11 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(help_text='lunes, martes..', max_length=15, verbose_name='dia de la semana')),
                ('fecha', models.DateTimeField()),
                ('estado', models.BooleanField(help_text='laborable o feriado', verbose_name='laborable')),
                ('descripcion', models.TextField(blank=True, max_length=250, verbose_name='(Opcional)')),
            ],
        ),
        migrations.CreateModel(
            name='Derivar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('C', 'Creado'), ('E', 'Enviado'), ('R', 'Recibido'), ('A', 'Archivado')], max_length=1)),
                ('comentario', models.TextField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_exp', models.IntegerField(verbose_name='Numero de Expediente')),
                ('nro_doc', models.CharField(max_length=95, verbose_name='codigo externo')),
                ('folios', models.IntegerField()),
                ('interesado', models.CharField(max_length=155)),
                ('asunto', models.CharField(max_length=180)),
                ('destinatario', models.CharField(max_length=180)),
                ('f_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('f_registro', models.DateTimeField(verbose_name='Fecha de Registro')),
                ('f_fint', models.DateTimeField(verbose_name='Fecha de fin del tramite')),
                ('observacion', models.TextField(max_length=150)),
                ('estado', models.CharField(choices=[('C', 'Creado'), ('E', 'Enviado'), ('R', 'Recivido'), ('A', 'Archivado')], max_length=1)),
                ('archivomotivo', models.TextField(max_length=1500)),
                ('roficina', models.CharField(max_length=250, verbose_name='Oficina donde se registro')),
                ('rusuario', models.CharField(max_length=250, verbose_name='Usuario que registro')),
            ],
        ),
        migrations.CreateModel(
            name='ExpedienteHistorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_salida', models.DateTimeField(verbose_name='Fecha de Salida')),
                ('o_origen', models.CharField(max_length=50, verbose_name='Oficina de origen')),
                ('o_destino', models.CharField(max_length=50, verbose_name='Ofina de destino')),
                ('f_recepcion', models.DateTimeField(verbose_name='Fecha de recepcion')),
                ('estado', models.CharField(max_length=250)),
                ('proveido', models.CharField(max_length=250)),
                ('ubicacion', models.CharField(max_length=150)),
                ('comentario', models.TextField(blank=True, help_text='maximo 1000 caracteres', max_length=1000, verbose_name='Comentario')),
                ('usuario', models.CharField(max_length=500)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitdapp.Expediente')),
            ],
        ),
        migrations.CreateModel(
            name='ExpedienteTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.TextField(blank=True, max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la Oficina', max_length=75, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=250, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre de la Institucion')),
                ('logo', models.ImageField(upload_to='Imagen', verbose_name='Imagen logo')),
                ('direccion', models.CharField(blank=True, max_length=850, verbose_name='direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Proveido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=250)),
                ('f_nacimiento', models.DateField(help_text='dias/mes/año', verbose_name='Fecha de Nacimiento')),
                ('cargo', models.CharField(max_length=25)),
                ('usuario', models.CharField(max_length=25, unique=True)),
                ('psw', models.CharField(max_length=25, verbose_name='PASSWORD')),
                ('admin', models.CharField(choices=[('N', 'NO'), ('S', 'SI')], max_length=1)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitdapp.Oficina')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajadorHistorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('oficina', models.CharField(max_length=25)),
                ('echo', models.CharField(max_length=25)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitdapp.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajadorPersmisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevo', models.BooleanField(default=1, help_text='permisos para crear nuevo', verbose_name='nuevo')),
                ('eliminar', models.BooleanField(default=1, help_text='permisos para eliminar', verbose_name='eliminar')),
                ('modificar', models.BooleanField(default=1, help_text='permisos para modificar', verbose_name='modificar')),
                ('imprimir', models.BooleanField(default=1, help_text='permisos para imprimir', verbose_name='imprimir')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitdapp.Formulario')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitdapp.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Tupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=85)),
                ('descripcion', models.TextField(blank=True, max_length=275)),
                ('autoridad', models.TextField(max_length=175)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tiempo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TupaRequisitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisito', models.CharField(max_length=45)),
                ('descripcion', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TupaVinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitdapp.TupaRequisitos')),
                ('tupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitdapp.Tupa')),
            ],
        ),
        migrations.AddField(
            model_name='expediente',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitdapp.Oficina'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitdapp.ExpedienteTipo'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tupa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitdapp.Tupa'),
        ),
        migrations.AddField(
            model_name='derivar',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitdapp.Expediente'),
        ),
        migrations.AddField(
            model_name='derivar',
            name='oficina',
            field=models.ManyToManyField(blank=True, editable=False, related_name='sitdapp_derivar_destino', to='sitdapp.Oficina'),
        ),
        migrations.AddField(
            model_name='derivar',
            name='oficinao',
            field=models.ManyToManyField(blank=True, editable=False, related_name='sitdapp_derivar_origen', to='sitdapp.Oficina'),
        ),
        migrations.AddField(
            model_name='derivar',
            name='proveido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitdapp.Proveido'),
        ),
    ]
