version: '2.1'

services:
  db:
    image: mysql
    container_name: "sitd_db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example   
  adminer:
    image: adminer
    container_name: "sitd_adminer"
    restart: always
    ports:
      - 9001:8080
  web:
    image: sitd_web
    container_name: "sitd_web"
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "9000:8000"
    depends_on:
      - db