version: '2.1'
services:

  db:
    image: mysql:8.0.26
    container_name: "sitd_db"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: dbsitd
      MYSQL_ROOT_PASSWORD: example   
    ports:
      - 9002:3306
  adminer:
    image: adminer
    container_name: "sitd_adminer"
    restart: always
    ports:
      - 9001:8080
  web:
    image: sitd_web
    container_name: "sitd_web"
    build:
      context: .
      dockerfile: Dockerfile    
    command: ./wait-for-it.sh db:3306 -- bash -c "python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8000"
    #volumes:
    #  - .:/code
    ports:
      - "9000:8000"
    depends_on:
      - db